DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]

# Django 4.0+ 使用 path/re_path
if DJANGO_VERSION >= (4, 0):
    from django.urls import re_path
    urlpatterns = [
        re_path(r'^controller/$', get_ueditor_controller)
    ]

# Django 1.8 到 3.2 保持原逻辑
elif DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

# 移除Django 1.8以下的兼容代码（不再支持）
else:
    # 现代Django版本不再需要此分支
    urlpatterns = []

contactApp/urls.py
from django.urls import path
from . import views

app_name = 'contactApp'

urlpatterns = [ 
    path('contact/', views.contact, name='contact'),      # 欢迎咨询
    path('recruit/', views.recruit, name='recruit'),      # 加入恒达
]

hengDaProject/urls.py
from django.contrib import admin
from django.urls import path
from homeApp.views import home # 导入首页对应的视图处理函数
from django.conf.urls import include # 导入include函数


urlpatterns = [
    path('admin/', admin.site.urls),                        # 管理员
    path('', home, name='home'),                            # 首页
    path('aboutApp/', include('aboutApp.urls')),            # 公司简介
    path('contactApp/', include('contactApp.urls')),        # 人才招聘
    path('newsApp/', include('newsApp.urls')),              # 新闻动态
    path('productsApp/', include('productsApp.urls')),      # 产品中心
    path('scienceApp/', include('scienceApp.urls')),        # 科研基地
    path('serviceApp/', include('serviceApp.urls')),        # 服务支持
    path('ueditor/',include('DjangoUeditor.urls')),         # 富文本服务
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

newsApp/urls.py
from django.urls import path
from . import views

app_name = 'newsApp'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'), # 新闻列表
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'), # 新闻列表
]

contactApp/models.py
from django.db import models
from django.utils import timezone

class Ad(models.Model):
    title = models.CharField(max_length=50, verbose_name='招聘岗位')
    description = models.TextField(verbose_name='岗位要求')
    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='发布时间')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '招聘广告'
        verbose_name_plural = '招聘广告'
        ordering = ('-publishDate', )

        
from datetime import datetime
 
class Resume(models.Model):
    name = models.CharField(max_length=20, verbose_name='姓名')
    personID = models.CharField(max_length=30, verbose_name='身份证号')
    sex = models.CharField(max_length=5, default='男', verbose_name='性别')
    email = models.EmailField(max_length=30, verbose_name='邮箱')
    birth = models.DateField(max_length=20,
                             default=datetime.strftime(datetime.now(),
                                                       "%Y-%m-%d"),
                             verbose_name='出生日期')
    edu = models.CharField(max_length=5, default='本科', verbose_name='学历')
    school = models.CharField(max_length=40, verbose_name='毕业院校')
    major = models.CharField(max_length=40, verbose_name='专业')
    position = models.CharField(max_length=40, verbose_name='申请职位')
    experience = models.TextField(blank=True,
                                  null=True,
                                  verbose_name='学习或工作经历')
    photo = models.ImageField(upload_to='contact/recruit/%Y_%m_%d',
                              verbose_name='个人照片')
    grade_list = (
        (1, '未审'),
        (2, '通过'),
        (3, '未通过'),
    )
    status = models.IntegerField(choices=grade_list,
                                 default=1,
                                 verbose_name='面试成绩')
    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='提交时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '简历'
        verbose_name_plural = '简历'
        ordering = ('-status', '-publishDate')


from django.db.models.signals import post_init,post_save
from django.dispatch import receiver
 
@receiver(post_init, sender=Resume)
def before_save_resume(sender, instance, **kwargs):
    instance.__original_status = instance.status

from django.core.mail import send_mail

@receiver(post_save, sender=Resume) 
def post_save_resume(sender, instance, **kwargs):
    email = instance.email                    # 应聘者邮箱
    EMAIL_FROM = '645224083@qq.com'           # 企业QQ邮箱
    if instance.__original_status==1 and instance.status==2:
        email_title = '通知：恒达科技招聘初试结果'
        email_body = '恭喜您通过本企业初试'
        send_status = send_mail(email_title, email_body, EMAIL_FROM, [email])
    elif instance.__original_status==1 and instance.status==3:
        email_title = '通知：恒达科技招聘初试结果'
        email_body = '很遗憾，您未能通过本企业初试，感谢您的关注'
        send_status = send_mail(email_title, email_body, EMAIL_FROM, [email])

contactApp/forms.py
from django import forms
from .models import Resume

class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ('name', 'sex', 'personID', 'email', 'birth', 'edu', 'school',
                  'major', 'experience', 'position', 'photo')
        sex_list = (
            ('男', '男'),
            ('女', '女'),
        )
        edu_list = (
            ('大专', '大专'),
            ('本科', '本科'),
            ('硕士', '硕士'),
            ('博士', '博士'),
            ('其它', '其它'),
        )
        widgets = {
            'sex': forms.Select(choices=sex_list),
            'edu': forms.Select(choices=edu_list),
            'photo': forms.FileInput(),
        }

contactApp/views.py
from django.shortcuts import render

def contact(request):
    return render(request, 'contact.html', {
        'active_menu': 'contact',
        'sub_menu': 'mycontact',
    })


from .models import Ad
from .forms import ResumeForm

def recruit(request):
    AdList = Ad.objects.all().order_by('-publishDate')
    if request.method == 'POST':
        resumeForm = ResumeForm(data=request.POST, files=request.FILES)
        if resumeForm.is_valid():
            resumeForm.save()
            return render(request, 'success.html', {
                'active_menu': 'contactus',
                'sub_menu': 'recruit',
            })
    else:
        resumeForm = ResumeForm()
    return render(
        request, 'recruit.html', {
            'active_menu': 'contactus',
            'sub_menu': 'recruit',
            'AdList': AdList,
            'resumeForm': resumeForm,
        })

contactApp/templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block title %}
欢迎咨询
{% endblock %}

{% block content %}
<link href="{% static 'css/contact.css' %}" rel="stylesheet">
<!-- 广告横幅 -->
<div class="container-fluid">
    <div class="row">
        <img class="img-responsive model-img" src="{% static 'img/contact.jpg' %}">
    </div>
</div>
<!-- 主体内容 -->
<div class="container">
    <div class="row row-3">
        <!-- 侧边导航栏 -->
        <div class="col-md-3">
            <div class="model-title">
                人才招聘
            </div>
            <div class="model-list">
                <ul class="list-group">
                    <li class="list-group-item" id="mycontact">
                        <a href="{% url 'contactApp:contact' %}">欢迎咨询</a>
                    </li>
                    <li class="list-group-item" id="recruit">
                        <a href="{% url 'contactApp:recruit' %}">加入恒达</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- 说明文字和图片 -->
        <div class="col-md-9">
            <div class="model-details-title">
                欢迎咨询
            </div>
            <div class="col-md-6">
                <div class="contact-left">
                    <h1>
                        <strong>荒坂科技有限公司</strong>
                        <span>HengDa Science and Technology</span>
                    </h1>
                    <ul>
                        <li><span>业务质询一：</span>111-111111</li>
                        <li><span>业务质询二：</span>222-222222</li>
                        <li><span>咨询电话：</span>0111-1111111</li>
                        <li><span>企业传真：</span>0222-2222222</li>
                        <li><span>地址：</span>夜之城</li>
                        <li><span>邮编：</span>2222-222222</li>
                        <li><span>网址：</span>
                            <a href="http://python3web.com">http://python3web.com</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-md-6 contact-right">
                <img class="img-responsive" src="{% static 'img/address.png' %}">
            </div>
        </div>
    </div>
</div>
{% endblock %}

contactApp/templates/recruit.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
加入荒坂
{% endblock %}

{% block content %}
<link href="{% static 'css/contact.css' %}" rel="stylesheet">
<script src="{% static 'js/layDate-v5.0.9/laydate.js' %}"></script>
<!-- 广告横幅 -->
<div class="container-fluid">
    <div class="row">
        <img class="img-responsive model-img" src="{% static 'img/contact.jpg' %}">
    </div>
</div>
<!-- 主体内容 -->
<div class="container">
    <div class="row row-3">
        <!-- 侧边导航栏 -->
        <div class="col-md-3">
            <div class="model-title">
                人才招聘
            </div>
            <div class="model-list">
                <ul class="list-group">
                    <li class="list-group-item" id="mycontact">
                        <a href="{% url 'contactApp:contact' %}">欢迎咨询</a>
                    </li>
                    <li class="list-group-item" id="recruit">
                        <a href="{% url 'contactApp:recruit' %}">加入荒坂</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- 说明文字和图片 -->
        <div class="col-md-9">
            <div class="model-details-title">
                加入荒坂
            </div>
            <div class="model-details">
                <div class="panel-group" id="accordion">
                    {% for ad in AdList %}
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="panel{{ad.id}}">
                            <h4 class="panel-title">
                                {% if forloop.first %}
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                        href="#collapse{{ad.id}}">
                                {% else %}
                                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion"
                                        href="#collapse{{ad.id}}">
                                {% endif %}
                                    {{ad.title}}
                                    </a>
                            </h4>
                        </div>
                        {% if forloop.first %}
                        <div id="collapse{{ad.id}}" class="panel-collapse collapse in">
                            {% else %}
                            <div id="collapse{{ad.id}}" class="panel-collapse collapse">
                                {% endif %}
                                <div class="panel-body">
                                    <p>{{ad.description}}</p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        请填写个人简历
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <form action="." name="resumeForm" class="form-horizontal" method="post" role="form" enctype="multipart/form-data">
                                {% csrf_token %}
                                <!-- 左侧 -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">你那无人在乎的姓名：</label>
                                        <div class="col-sm-9">
                                            {{resumeForm.name|add_class:"form-control"|attr:"placeholder=请填写姓名"}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">身份证号：</label>
                                        <div class="col-sm-9">
                                            {{resumeForm.personID|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">性别：</label>
                                        <div class="col-sm-9">
                                            {{resumeForm.sex|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">出生日期：</label>
                                        <div class="col-sm-9">
                                            {{resumeForm.birth|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">邮箱：</label>
                                        <div class="col-sm-9">
                                            {{resumeForm.email|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">学历：</label>
                                        <div class="col-sm-9">
                                            {{resumeForm.edu|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">毕业学校：</label>
                                        <div class="col-sm-9">
                                            {{resumeForm.school|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">专业：</label>
                                        <div class="col-sm-9">
                                            {{resumeForm.major|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">申请职位：</label>
                                        <div class="col-sm-9">
                                            {{resumeForm.position|add_class:"form-control"}}
                                        </div>
                                    </div>
                                </div>
                                <!-- 右侧 -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="col-sm-12" style="text-align:center">
                                            <img id="profileshow" style="width:120px" src="{% static 'img/sample.png' %}">
                                        </div>
                                        <label class="col-sm-5 control-label">上传证件照片：</label>
                                        {{resumeForm.photo}}
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-12 control-label">学习或工作经历：</label>
                                        <div class="col-sm-12">
                                            {{resumeForm.experience|add_class:"form-control"}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <center><input type="submit" class="btn btn-primary" value="提交" /></center>
                                </div>
                            </form>
                        </div>
                    </div>    
                </div>
    
            </div>
        </div>
    </div>
    <script>
        laydate.render({
            elem: '#id_birth'
        });
    </script>
    <script>
        $(function () {
            $('#id_photo').on('change', function () {
                var r = new FileReader();
                f = document.getElementById('id_photo').files[0];
                r.readAsDataURL(f);
                r.onload = function (e) {
                    document.getElementById('profileshow').src = this.result;
                };
            });
        });
    </script>
    {% endblock %}

contactApp/templates/success.html
{% extends "base.html" %}
{% load static %}

{% block title %}
人才招聘
{% endblock %}

{% block content %}
<!-- 主体内容 -->
<div class="container">
    <div class="row">
        <div class="alert alert-success">
            <strong>Loser!</strong> 你那废物简历信息已成功被筛掉，初试失败的结果会让您自己过来上门接受。
        </div>
    </div>
</div>
{% endblock %}