DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]

# Django 4.0+ 使用 path/re_path
if DJANGO_VERSION >= (4, 0):
    from django.urls import re_path
    urlpatterns = [
        re_path(r'^controller/$', get_ueditor_controller)
    ]

# Django 1.8 到 3.2 保持原逻辑
elif DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

# 移除Django 1.8以下的兼容代码（不再支持）
else:
    # 现代Django版本不再需要此分支
    urlpatterns = []

aboutApp/urls.py
from django.urls import path
from . import views

app_name = 'aboutApp'  # 设置应用名

urlpatterns = [
    path('survey/', views.survey, name='survey'),   # 企业概况
    path('honor/', views.honor, name='honor'),      # 荣誉资质
]

contactApp/urls.py
from django.urls import path
from . import views

app_name = 'contactApp'

urlpatterns = [ 
    path('contact/', views.contact, name='contact'),      # 欢迎咨询
    path('recruit/', views.recruit, name='recruit'),      # 加入恒达
]

hengDaProject/urls.py
from django.contrib import admin
from django.urls import path
from homeApp.views import home # 导入首页对应的视图处理函数
from django.conf.urls import include # 导入include函数


urlpatterns = [
    path('admin/', admin.site.urls),                        # 管理员
    path('', home, name='home'),                            # 首页
    path('aboutApp/', include('aboutApp.urls')),            # 公司简介
    path('contactApp/', include('contactApp.urls')),        # 人才招聘
    path('newsApp/', include('newsApp.urls')),              # 新闻动态
    path('productsApp/', include('productsApp.urls')),      # 产品中心
    path('scienceApp/', include('scienceApp.urls')),        # 科研基地
    path('serviceApp/', include('serviceApp.urls')),        # 服务支持
    path('ueditor/',include('DjangoUeditor.urls')),         # 富文本服务
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

newsApp/urls.py
from django.urls import path
from . import views

app_name = 'newsApp'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'), # 新闻列表
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'), # 新闻列表
]

scienceApp/urls.py
from django.urls import path
from . import views

app_name = 'scienceApp'

urlpatterns = [
    path('science/', views.science, name='science'),  # 科研基地
]

serviceApp/urls.py
from django.urls import path
from . import views

app_name = 'serviceApp'

urlpatterns = [
    path('download/', views.download, name='download'),  # 资料下载
    path('platform/', views.platform, name='platform'),  # 人脸识别开放平台
    path('getDoc/<int:id>/', views.getDoc, name='getDoc'), # 下载文件
    path('facedetect/', views.facedetect, name='facedetect'),  # 人脸检测api
    path('facedetectDemo/', views.facedetectDemo, name='facedetectDemo'),  # 在线人脸检测
]




templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>荒坂科技|{% block title %}{% endblock %} </title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>
    <div class="container top">
        <div class="row">
            <div class="col-md-6">
                <a>
                    <img class="img-responsive" src="{% static 'img/logo.jpg' %}">
                </a>
            </div>
            <div class="col-md-3 hidden-xs">
                <a class="phone ant">
                    <span class="glyphicon glyphicon-phone"></span>电话：17520271486 &nbsp; &nbsp;
                </a>
            </div>
            <div class="col-md-3 hidden-xs">
                <a class="mail ant">
                    <span class="glyphicon glyphicon-envelope"></span>邮箱：itis_mygo@outlook.com
                </a>
            </div>
        </div>
    </div>

    <!-- 导航条 -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example"
                    aria-expanded="false">
                    <span>导航栏</span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example">
                <ul class="nav navbar-nav" style="width:100%;">
                    <li class="nav-top" id='home'>
                        <a href="{% url 'home' %}">首页</a>
                    </li>
                    <li class="dropdown nav-top" id='about'>
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">
                            公司简介</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'aboutApp:survey' %}">企业概况</a></li>
                            <li><a href="{% url 'aboutApp:honor' %}">荣誉资质</a></li>
                        </ul>
                    </li>
                    <li class="dropdown nav-top">
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">
                            新闻动态</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'newsApp:news' 'company' %}">企业要闻</a></li>
                            <li><a href="{% url 'newsApp:news' 'industry' %}">行业新闻</a></li>
                            <li><a href="{% url 'newsApp:news' 'notice' %}">通知公告</a></li>
                        </ul>
                    </li>
                    <li class="dropdown nav-top" id='products'>
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">
                            产品中心</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'productsApp:products' 'robot' %}">
                                    家用机器人</a></li>
                            <li><a href="{% url 'productsApp:products' 'monitor' %}">
                                    智能监控</a></li>
                            <li><a href="{% url 'productsApp:products' 'face' %}">
                                    人脸识别解决方案</a></li>
                        </ul>
                    </li>
                    <li class="dropdown nav-top" id='service'>
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">
                            服务支持</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'serviceApp:download' %}">
                                    资料下载</a></li>
                            <li><a href="{% url 'serviceApp:platform' %}">
                                    人脸识别开放平台</a></li>
                        </ul>
                    </li>
                    <li class="nav-top" id='science'>
                        <a href="{% url 'scienceApp:science' %}">科研基地</a>
                    </li>
                    <li class="dropdown nav-top" id='contact'>
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">人才招聘</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'contactApp:contact' %}">欢迎咨询</a></li>
                            <li><a href="{% url 'contactApp:recruit' %}">加入荒坂</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="line"></div>

    {% block content %}
    {% endblock %}

    <div class="row" id="map-footer">
        <div class="col-md-2">
            <dl>
                <dt>公司简介</dt>
                <dd><a href="{% url 'aboutApp:survey' %}">企业概况</a></dd>
                <dd><a href="{% url 'aboutApp:honor' %}">荣誉资质</a></dd>
            </dl>
        </div>
        <div class="col-md-2">
            <dl>
                <dt>产品中心</dt>
                <dd><a href="{% url 'productsApp:products' 'robot' %}">家用机器人</a></dd>
                <dd><a href="{% url 'productsApp:products' 'monitor' %}">智能监控</a></dd>
                <dd><a href="{% url 'productsApp:products' 'face' %}">人脸识别解决方案</a></dd>
            </dl>
        </div>
        <div class="col-md-2">
            <dl>
                <dt>服务支持</dt>
                <dd><a href="{% url 'serviceApp:download' %}">资料下载</a></dd>
                <dd><a href="{% url 'serviceApp:platform' %}">人工智能开放平台</a></dd>
            </dl>
        </div>
        <div class="col-md-2">
            <dl>
                <dt>人才招聘</dt>
                <dd><a href="{% url 'contactApp:contact' %}">欢迎咨询</a></dd>
                <dd><a href="{% url 'contactApp:recruit' %}">加入荒坂</a></dd>
            </dl>
        </div>
        <div class="col-md-4" id="wx">
            <p>扫描二维码，关注我们</p>
            <img class="qrimg" src="{% static 'img/qr.png' %}" alt="wx">
            <p>客服热线：<b style="font-size:20px">17520271486</b></p>
        </div>
    </div>

    <script>
        $(function () {
            $(".dropdown").mouseover(function () {
                $(this).addClass("open");
            });
            $(".dropdown").mouseleave(function () {
                $(this).removeClass("open");
            });
        });
    </script>

    <script type="text/JavaScript">
        $('#{{active_menu}}').addClass("active");
    </script>

    <script type="text/JavaScript">
        $('#{{sub_menu}}').addClass("active");
    </script>
</body>

</html>